### ISSUE TITLE
Extender y modificar el analizador

### ISSUE THREAD

**Issue by alu0100204148** [alu0100204148/AnalizadorDPR#6]
Extienda y modifique el analizador para que acepte el lenguaje descrito por la gramática EBNF del lenguaje PL/0 que se describe en la entrada de la Wikipedia Recursive descent parser. Procure que el arbol generado refleje la asociatividad correcta para las diferencias y las divisiones. No es necesario que el lenguaje sea exactamente igual pero debería ser parecido. Tener los mismos constructos.

**Comment by alu0100204148** [comment]
Está todo listo y funcionando, solo queda ampliar el código de el fichero que ya se está usando.

**Comment by mluisdelgado** [comment]
Correcto, añadidos calculos de restas y divisiones.
